import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {ReposFilterableGrid} from '../components/ReposFilterableGrid'
import {Box, Typography} from '@mui/material'
import * as labels from '../assets/labels'
import React from 'react'

const Home: NextPage = () => {
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box className={styles.description}>
        <Typography variant={'h4'} >
            {labels.lastWeekCreatedGithubRepos}
        </Typography>
      </Box>
      
      <ReposFilterableGrid />
      
    </div>
  )
}

export default Home
